name: CI

on:
  push:
    branches: [ main ] # Adjust branch name if needed
  pull_request:
    branches: [ main ] # Adjust branch name if needed

jobs:
  test:
    if: false      # disable Python tests entirely
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"] # Adjust Python versions as needed

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies (with PQC extras)
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[pqc]"
        pip install pytest black flake8 pytest-cov
    - name: Lint with black
      run: |
        black --check src/ tests/
    - name: Lint with flake8
      run: |
        flake8 src/ tests/
    - name: Test with pytest
      run: |
        python -m pytest -v --cov=src tests/ 